POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzMyNzE5NDAxLCJ1c2VySWQiOjF9.8EPQGk-cR5G4z8q-gWLimOGtpMGrO8BOP2eN5ByRoac

{
    "title": "Test event1!!",
    "description": "A test event!!!",
    "location": "Another test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}