POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q2QGV4YW1wbGUuY29tIiwiZXhwIjoxNzMyOTU4Mzc2LCJ1c2VySWQiOjN9.Rz1Q9fp8sNc499oQ21sCrIRqfuXF84q21e9qfIJWU4g

{
    "title": "Event for dogs!!",
    "description": "Event for dogs party",
    "location": "Riga-Latvia",
    "dateTime": "2025-01-01T15:30:00.000Z"
}